name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Alpine
      uses: jirutka/setup-alpine@v1
      with:
        branch: v3.17

    - name: Install build dependencies
      run: apk add build-base go upx
      shell: alpine.sh --root {0}

    - name: Get code dependencies
      run: go get .
      shell: alpine.sh {0}

    - name: Get tag
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

    - name: Build
      run: go build -o EternalPatcher -ldflags="-s -w -X 'main.Version=$RELEASE_VERSION'" .
      shell: alpine.sh {0}

    - name: Pack with UPX
      run: upx --best EternalPatcher
      shell: alpine.sh {0}

    - name: Upload binary
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.ACTIONS_TOKEN }}
        file_glob: true
        file: "**/EternalPatcher"
        tag: ${{ github.ref }}
