name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release-ubuntu:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Alpine
      uses: jirutka/setup-alpine@v1
      with:
        branch: v3.17

    - name: Install build dependencies
      run: apk add build-base go upx
      shell: alpine.sh --root {0}

    - name: Get code dependencies
      run: go get .
      shell: alpine.sh {0}

    - name: Get tag
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

    - name: Build
      run: go build -o EternalPatcher -tags netgo -ldflags="-s -w -X 'main.Version=$RELEASE_VERSION'" .
      shell: alpine.sh {0}

    - name: Pack with UPX
      run: upx --best EternalPatcher
      shell: alpine.sh {0}

    - name: Upload binary
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file_glob: true
        file: "**/EternalPatcher"
        tag: ${{ github.ref }}

  release-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install UPX
      run: choco install upx

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.20'

    - name: Get dependencies
      run: go get .

    - name: Get tag
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      shell: bash

    - name: Build
      run: go build -o EternalPatcher.exe -ldflags="-s -w -X 'main.Version=$RELEASE_VERSION'" .
      shell: bash

    - name: Pack with UPX
      run: upx --best EternalPatcher.exe

    - name: Upload binary
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file_glob: true
        file: "**/EternalPatcher.exe"
        tag: ${{ github.ref }}
